# Configuration for Task 15 (Theoretical)
part1:  
  N: 100000
  N_b: 100 #1/1000
  gaussian:
    mean_k: 20
    std_k: 8
  uniform:
    k_min: 4
    k_max: 36
  realizations: 30

part2:
  N: 100000 
  mean_k: 4
  gammas: [2.01, 2.2, 2.4, 2.6, 2.8, 3.0, 5.0, 100.0] # 100.0 acts as infinity
  f: 0.001 #1/1000
  realizations: 30
